language: java

script:
 - ant;
 - ant test;

sudo: required

services:
 - docker

before_install:
 - docker build ./ -t denni9th/green
 - docker run 127.0.0.1:4567 denni9th/green /bin/sh -c "cd /green/; ant; ant test;"

